name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Setup Android SDK Tools
      uses: android-actions/setup-android@v2.0.2
    - name: Setup Android NDK
      # You may pin to the exact commit or the version.
      # uses: nttld/setup-ndk@7ecec22caa4fe94863d2dca55455b4d9ccded495
      uses: nttld/setup-ndk@v1.0.2
      with:
        # Exact version to use
        ndk-version: r22
    - name: get-cmake
      # You may pin to the exact commit or the version.
      # uses: lukka/get-cmake@ce884ff4748bc525a2177d60e239360355738b4d
      uses: lukka/get-cmake@v3.19.2  
    - name: Build with Gradle
      run: ./gradlew build
