name: release

on:
  workflow_run:
    workflows: ["Android CI"]
    types:
      - completed
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.workflow_run.conclusion == 'success' && startsWith(github.event.workflow_run.head_branch, 'v') && contains(github.event.workflow_run.head_branch, '.')
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.sha }}-build
          path: ./artifacts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Extract Release Files
        run: |
          mkdir -p ./release
          cp ./artifacts/fakelinker-lib-debug.aar ./release/fakelinker-debug.aar
          cp ./artifacts/fakelinker-lib-release.aar ./release/fakelinker-release.aar
      - name: Release Tag
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/fakelinker-debug.aar
            release/fakelinker-release.aar
          name: ${{ github.event.workflow_run.head_branch }}
          tag_name: ${{ github.event.workflow_run.head_branch }}
